docker-build-master:
  stage: build
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy-service-master:
  stage: deploy
  script:
    - apk add --update curl
    - curl -XPOST http://host.docker.internal:9000/api/webhooks/f9ab220c-0563-4d0f-911e-3b905bfe3872
  only:
    - master
